CREATE TABLE IF NOT EXISTS category
(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS place
(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL
);